version: '3.8'

services:
  backend:
    image: api-ventas-admin:latest
    build: ./api-ventas-admin
    container_name: app-back
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql_db:3306/BD_DITTO?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    depends_on:
      - mysql_db
    networks:
      - app_network

  frontend:
    image: appsistemaventaadmin:latest
    build: ./AppSistemaVentaAdmin
    container_name: app-front
    ports:
      - "4200:80"
    depends_on:
      - backend
    networks:
      - app_network

  mysql_db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=BD_DITTO
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql/:/docker-entrypoint-initdb.d/
    networks:
      - app_network

volumes:
  mysql_data:
    
networks:
  app_network:
    driver: bridge